name: 'Build Windows Installer MSI from exe file'
description: 'Build and release Windows installer on github release page'
inputs:
  exefile:
    description: 'exe file to wrap in the MSI installer'
    required: true
  version:
    description: 'what version to use for the built MSI'
    default: '0.0.1'
runs:
  using: 'node16'
  main: 'dist/index.js'
icon: wind
color: purple
